// Owner snapshot-rebuild golden corpus (access Phase 2; owner-regression review:
// "golden corpus blind spots — the rebuild is not covered").
//
// ownerSqlCorpus.ts proves the owner's READ SQL is byte-identical. The rebuild
// (rebuildCohortMembership, the owner's Rebuild and the post-sync auto-rebuild)
// is not a read runner, and Phase 2 adds work to it on purpose: the campaign
// scope (fact_campaign_scope) after activation and the retention ALTERs. This
// harness drives a rebuild with createRecordingClickHouse and a fake
// service-role Supabase and records, IN ORDER (the rebuild is sequential):
//   * every ClickHouse statement { kind, query, query_params, format, table, values };
//   * the Supabase RPC names.
// ownerRebuildGolden.test.ts removes the Phase-2 additions
// (isPhase2RebuildAddition / PHASE2_REBUILD_RPCS) from a recording of the
// current code and compares the rest byte for byte with
// src/test/fixtures/owner-rebuild-golden.json, recorded from the UNMODIFIED
// base code (4b4057e). So the owner's classifier INSERT, counts, version diff,
// validation and the claim / complete / fail sequence cannot drift unnoticed.
//
// Vitest-free on purpose (the base fixture is generated by bundling this file
// with the base tree's rebuild): the caller pins the clock.

import { createHash } from "node:crypto";
import { createRecordingClickHouse, type RecordedStatement } from "./recordingClickHouse.ts";
import type {
  ClickHouseClientLike,
  SupabaseLikeClient,
  SupabaseQueryBuilder,
  SupabaseQueryResult,
} from "../../../supabase/functions/_shared/clickhouse/types.ts";

export const OWNER_REBUILD_CORPUS_FORMAT = "owner-rebuild-golden/v1";
export const OWNER_REBUILD_BASE_COMMIT = "4b4057e";
export const OWNER_REBUILD_NOW = "2026-10-06T00:00:00.000Z";
export const OWNER_REBUILD_TENANT = "owner-golden-tenant-0001";
/** Literal on purpose: the corpus must not move when a constant is refactored. */
const CLASSIFICATION_VERSION = "cohort_classifier_v3_platform";
/** What the fake fingerprint hashes to (warehouse_hash "golden"). */
const CURRENT_WAREHOUSE_VERSION = "wh_golden";

/** The rebuild's public signature, as both the base and the current code accept it. */
export type OwnerRebuildFn = (input: {
  authUserId: string;
  supabase: SupabaseLikeClient;
  clickhouse: ClickHouseClientLike;
  force?: boolean;
}) => Promise<unknown>;

export interface OwnerRebuildScenario {
  readonly id: string;
  /** clickhouse_cohort_snapshot_state before the call (null: never built). */
  readonly previous: Readonly<Record<string, unknown>> | null;
  readonly force: boolean;
  readonly validation: "PASS" | "FAIL";
}

const VALIDATION = { status: "PASS", duplicate_users: 0, dynamic_users: 100, materialized_users: 100 };

function completedState(warehouseVersion: string, classificationVersion: string, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    auth_user_id: OWNER_REBUILD_TENANT,
    snapshot_name: "fact_user_cohorts",
    status: "completed",
    active_warehouse_version: warehouseVersion,
    active_classification_version: classificationVersion,
    active_generated_at: "2026-10-05T23:00:00.000Z",
    building_warehouse_version: null,
    building_classification_version: null,
    started_at: "2026-10-05T22:59:00.000Z",
    finished_at: "2026-10-05T23:00:00.000Z",
    duration_ms: 60000,
    users_classified: 100,
    rows_inserted: 100,
    duplicate_users: 0,
    removed_or_invalidated: 0,
    source_transactions: 500,
    source_unique_users: 120,
    last_error: null,
    diagnostics: { validation: VALIDATION },
    ...extra,
  };
}

/** The owner's rebuild situations: a new warehouse version over an older
 * snapshot, the very first build, the short-circuit of a current snapshot (with
 * and without a recorded campaign scope), a forced rebuild, and a validation
 * failure (the snapshot is not activated). */
export const OWNER_REBUILD_SCENARIOS: readonly OwnerRebuildScenario[] = Object.freeze([
  { id: "full/previous=old", previous: completedState("wh_old", "cohort_classifier_v2_authoritative_fields"), force: false, validation: "PASS" },
  { id: "full/first_build", previous: null, force: false, validation: "PASS" },
  { id: "full/validation_fail", previous: completedState("wh_old", CLASSIFICATION_VERSION), force: false, validation: "FAIL" },
  {
    id: "current/campaign_scope_recorded",
    previous: completedState(CURRENT_WAREHOUSE_VERSION, CLASSIFICATION_VERSION, {
      active_validation: VALIDATION, active_campaign_scope_version: "campaign_scope_v1", fresh_verified_at: OWNER_REBUILD_NOW,
    }),
    force: false,
    validation: "PASS",
  },
  // A current snapshot built before Phase 2: the current code fills only the campaign scope in.
  { id: "current/pre_phase2_state", previous: completedState(CURRENT_WAREHOUSE_VERSION, CLASSIFICATION_VERSION), force: false, validation: "PASS" },
  { id: "force/current", previous: completedState(CURRENT_WAREHOUSE_VERSION, CLASSIFICATION_VERSION), force: true, validation: "PASS" },
  {
    id: "full/after_failed_build",
    previous: completedState("wh_old", CLASSIFICATION_VERSION, {
      status: "failed", building_warehouse_version: CURRENT_WAREHOUSE_VERSION, building_classification_version: CLASSIFICATION_VERSION,
      last_error: "Cohort membership validation failed; active snapshot was not changed.",
    }),
    force: false,
    validation: "PASS",
  },
]);

/** Fake warehouse answers, from the statement text alone. */
function respond(scenario: OwnerRebuildScenario) {
  return (statement: RecordedStatement): unknown[] => {
    const query = statement.query;
    if (query.includes("warehouse_hash")) {
      return [{ transaction_count: 500, unique_users: 120, max_row_version: "99", max_source_updated_at: "2026-10-05 23:00:00", warehouse_hash: "golden" }];
    }
    if (query.includes("(SELECT count() FROM dynamic) dynamic_users")) {
      return [{
        dynamic_users: 100,
        materialized_users: scenario.validation === "PASS" ? 100 : 99,
        duplicate_users: 0,
        missing_users: scenario.validation === "PASS" ? 0 : 1,
        extra_users: 0,
      }];
    }
    // fact_campaign_scope (current code only): evidence, then a matching read-back.
    if (query.includes("AS cid")) return [{ cid: "120210000000001", campaign_path: "soulmate-sketch", users: 5 }];
    if (query.includes("AS scope_rows")) return [{ scope_rows: 1, campaign_ids: 1, bad_resolved: 0, bad_mixed: 0, anchor_total: 5 }];
    if (query.includes("count() - uniqExact(canonical_user_id)")) return [{ c: 0 }];
    if (query.includes("common_users")) return [{ common_users: 90, unchanged_users: 80 }];
    if (query.includes("count() AS c")) return [{ c: 100 }];
    return [];
  };
}

/** Service-role Supabase: the snapshot state row for every read of it, empty
 * results elsewhere (the campaign alias map), `true` for every RPC. */
function fakeSupabase(previous: Readonly<Record<string, unknown>> | null, rpc: string[]): SupabaseLikeClient {
  return {
    from(table: string) {
      const rows = () => (table === "clickhouse_cohort_snapshot_state" && previous ? [JSON.parse(JSON.stringify(previous)) as Record<string, unknown>] : []);
      const builder = {
        select: () => builder,
        eq: () => builder,
        is: () => builder,
        order: () => builder,
        limit: () => builder,
        in: () => builder,
        maybeSingle: async (): Promise<SupabaseQueryResult> => ({ data: rows()[0] ?? null, error: null }),
        single: async (): Promise<SupabaseQueryResult> => ({ data: rows()[0] ?? null, error: null }),
        then: (resolve: (value: SupabaseQueryResult) => unknown, reject?: (reason: unknown) => unknown) =>
          Promise.resolve({ data: rows(), error: null }).then(resolve, reject),
      } as unknown as SupabaseQueryBuilder;
      return builder;
    },
    async rpc(functionName: string): Promise<SupabaseQueryResult> {
      rpc.push(functionName);
      return { data: true, error: null };
    },
  };
}

export interface OwnerRebuildStatement {
  kind: RecordedStatement["kind"];
  /** Key into OwnerRebuildCorpus.sql. */
  query: string;
  query_params: Record<string, unknown>;
  format?: string;
  table?: string;
  values?: unknown;
}

export interface OwnerRebuildRecord {
  /** "resolved" | "rejected:<ErrorName>". */
  outcome: string;
  rpc: string[];
  statements: OwnerRebuildStatement[];
}

export interface OwnerRebuildCorpus {
  format: string;
  base_commit: string;
  now: string;
  tenant: string;
  scenarios: Record<string, OwnerRebuildRecord>;
  sql: Record<string, string>;
}

export function ownerRebuildTextKey(text: string): string {
  return `q_${createHash("sha256").update(text, "utf8").digest("hex").slice(0, 16)}`;
}

/** Objects with sorted keys (recursively); arrays keep their order. */
function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      const item = (value as Record<string, unknown>)[key];
      if (item !== undefined) out[key] = canonical(item);
    }
    return out;
  }
  return value;
}

function toStatement(statement: RecordedStatement, sql: Record<string, string>): OwnerRebuildStatement {
  const key = ownerRebuildTextKey(statement.query);
  if (sql[key] !== undefined && sql[key] !== statement.query) throw new Error(`owner rebuild corpus: content key collision on ${key}`);
  sql[key] = statement.query;
  const out: OwnerRebuildStatement = { kind: statement.kind, query: key, query_params: canonical(statement.params ?? {}) as Record<string, unknown> };
  if (statement.format !== undefined) out.format = statement.format;
  if (statement.table !== undefined) out.table = statement.table;
  if (statement.values !== undefined) out.values = canonical(statement.values);
  return out;
}

/** Runs every scenario with `rebuild`. The caller pins Date to OWNER_REBUILD_NOW. */
export async function recordOwnerRebuildCorpus(rebuild: OwnerRebuildFn, scenarios: readonly OwnerRebuildScenario[] = OWNER_REBUILD_SCENARIOS): Promise<OwnerRebuildCorpus> {
  if (new Date().toISOString() !== OWNER_REBUILD_NOW) throw new Error(`owner rebuild corpus: pin the clock to ${OWNER_REBUILD_NOW} first`);
  const sql: Record<string, string> = {};
  const records: Record<string, OwnerRebuildRecord> = {};
  for (const scenario of scenarios) {
    const clickhouse = createRecordingClickHouse(respond(scenario));
    const rpc: string[] = [];
    let outcome = "resolved";
    try {
      await rebuild({ authUserId: OWNER_REBUILD_TENANT, supabase: fakeSupabase(scenario.previous, rpc), clickhouse, force: scenario.force });
    } catch (error) {
      outcome = `rejected:${error instanceof Error ? error.name : typeof error}`;
    }
    records[scenario.id] = { outcome, rpc, statements: clickhouse.statements.map((statement) => toStatement(statement, sql)) };
  }
  const sortedSql: Record<string, string> = {};
  for (const key of Object.keys(sql).sort()) sortedSql[key] = sql[key];
  return {
    format: OWNER_REBUILD_CORPUS_FORMAT,
    base_commit: OWNER_REBUILD_BASE_COMMIT,
    now: OWNER_REBUILD_NOW,
    tenant: OWNER_REBUILD_TENANT,
    scenarios: records,
    sql: sortedSql,
  };
}

export function serializeOwnerRebuildCorpus(corpus: OwnerRebuildCorpus): string {
  return `${JSON.stringify(corpus, null, 2)}\n`;
}

// ---- Phase-2 additions ---------------------------------------------------------

/** RPCs Phase 2 adds around the owner's claim / complete / fail sequence. */
export const PHASE2_REBUILD_RPCS: ReadonlySet<string> = new Set([
  "observe_clickhouse_cohort_snapshot_fingerprint",
  "set_clickhouse_campaign_scope_version",
]);

/** A statement Phase 2 adds to the rebuild: the fact_campaign_scope build
 * (ensure, evidence over fact_user_cohorts, existing ids, insert, read-back) or
 * the retention ALTER of either snapshot table. Everything else must be the
 * base statement, in order. */
export function isPhase2RebuildAddition(statement: OwnerRebuildStatement, sql: Record<string, string>): boolean {
  const text = sql[statement.query] ?? "";
  if (statement.kind === "insert") return statement.table === "fact_campaign_scope";
  if (/\bfact_campaign_scope\b/.test(text)) return true;
  // campaignScope.ts CAMPAIGN_SCOPE_EVIDENCE_SQL (reads the snapshot itself).
  if (text.includes(" AS cid,") && text.includes("GROUP BY cid, campaign_path")) return true;
  return /^ALTER TABLE (fact_user_cohorts|fact_campaign_scope) DELETE WHERE auth_user_id = \{auth_user_id:String\}\n  AND generated_at < /.test(text);
}

/** One scenario of `actual` with the Phase-2 additions removed (statement keys
 * re-pointed into `actual.sql`), for an ordered comparison with the base. */
export function withoutPhase2Additions(record: OwnerRebuildRecord, sql: Record<string, string>): OwnerRebuildRecord {
  return {
    outcome: record.outcome,
    rpc: record.rpc.filter((name) => !PHASE2_REBUILD_RPCS.has(name)),
    statements: record.statements.filter((statement) => !isPhase2RebuildAddition(statement, sql)),
  };
}
